### ISSUE TITLE
Flanneld overrides subnet in etcd

### ISSUE THREAD

**Issue by devent** [flannel-io/flannel#813] opened 2017-09-14 11:24 UTC
## Expected Behavior

Start flanneld on 192.168.56.200 (node-0)
flannel.1 should have 10.2.43.0
Start flanneld on 192.168.56.201 (node-1)
flannel.1 should have 10.2.44.0 (different subnet)

## Current Behavior

Start flanneld on 192.168.56.200 (node-0)
flannel.1 have 10.2.43.0
Start flanneld on 192.168.56.201 (node-1)
flannel.1 have 10.2.43.0 (same subnet)

## Steps to Reproduce (for bugs)

1. 2 nodes etcd cluster
2. Use etcd-gateway on each node to access the etcd cluster
3. install on each node flanneld
4. start flanneld on each node

## Context

I have for testing purposes 2 virtualbox nodes. If I start flanneld on node-0, I can see the subnet:

```
# /usr/local/bin/flanneld --etcd-endpoints=https://192.168.56.200:22379 --etcd-prefix=/atomic.io/network --iface=enp0s8 -v=3 --ip-masq 
I0914 13:19:13.991004   16806 main.go:459] Using interface with name enp0s8 and address 192.168.56.200
I0914 13:19:13.991079   16806 main.go:476] Defaulting external address to interface address (192.168.56.200)
2017-09-14 13:19:13.993870 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
I0914 13:19:13.993984   16806 main.go:226] Created subnet manager: Etcd Local Manager with Previous Subnet: 10.2.43.0/24
I0914 13:19:13.993999   16806 main.go:229] Installing signal handlers
I0914 13:19:14.045113   16806 main.go:330] Found network config - Backend type: vxlan
I0914 13:19:14.057389   16806 local_manager.go:177] Found lease (10.2.43.0/24) matching previously leased subnet, reusing
I0914 13:19:14.065349   16806 ipmasq.go:51] Adding iptables rule: -s 10.2.0.0/16 -d 10.2.0.0/16 -j RETURN
I0914 13:19:14.068678   16806 ipmasq.go:51] Adding iptables rule: -s 10.2.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE
I0914 13:19:14.071184   16806 ipmasq.go:51] Adding iptables rule: ! -s 10.2.0.0/16 -d 10.2.43.0/24 -j RETURN
I0914 13:19:14.073192   16806 ipmasq.go:51] Adding iptables rule: ! -s 10.2.0.0/16 -d 10.2.0.0/16 -j MASQUERADE
I0914 13:19:14.074796   16806 main.go:279] Wrote subnet file to /run/flannel/subnet.env
I0914 13:19:14.074916   16806 main.go:284] Finished starting backend.
I0914 13:19:14.075167   16806 vxlan_network.go:56] Watching for L3 misses
I0914 13:19:14.075185   16806 vxlan_network.go:64] Watching for new subnet leases
I0914 13:19:14.081725   16806 main.go:367] Waiting for 22h59m59.976947556s to renew lease
# curl  --cacert "$ETCDCTL_CACERT" --cert "$ETCDCTL_CERT" --key "$ETCDCTL_KEY" "https://192.168.56.200:22379/v2/keys/atomic.io/network/subnets/"
{"action":"get","node":{"key":"/atomic.io/network/subnets","dir":true,"nodes":[{"key":"/atomic.io/network/subnets/10.2.43.0-24","value":"{\"PublicIP\":\"192.168.56.200\",\"BackendType\":\"vxlan\",\"BackendData\":{\"VtepMAC\":\"aa:a8:a0:d0:9d:11\"}}","expiration":"2017-09-15T11:19:14.058638646Z","ttl":86392,"modifiedIndex":37,"createdIndex":37}],"modifiedIndex":7,"createdIndex":7}}
```

But then I start flanneld on node-1, the same subnet is used and the key in etcd is overridden.

```
# /usr/local/bin/flanneld --etcd-endpoints=https://192.168.56.201:22379 --etcd-prefix=/atomic.io/network --iface=enp0s8 -v=3 --ip-masq 
I0914 13:21:03.422713   10227 main.go:459] Using interface with name enp0s8 and address 192.168.56.201
I0914 13:21:03.422760   10227 main.go:476] Defaulting external address to interface address (192.168.56.201)
2017-09-14 13:21:03.423713 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
I0914 13:21:03.423766   10227 main.go:226] Created subnet manager: Etcd Local Manager with Previous Subnet: 10.2.43.0/24
I0914 13:21:03.423771   10227 main.go:229] Installing signal handlers
I0914 13:21:03.472953   10227 main.go:330] Found network config - Backend type: vxlan
I0914 13:21:03.481689   10227 local_manager.go:177] Found lease (10.2.43.0/24) matching previously leased subnet, reusing
I0914 13:21:03.487466   10227 ipmasq.go:51] Adding iptables rule: -s 10.2.0.0/16 -d 10.2.0.0/16 -j RETURN
I0914 13:21:03.489211   10227 ipmasq.go:51] Adding iptables rule: -s 10.2.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE
I0914 13:21:03.490963   10227 ipmasq.go:51] Adding iptables rule: ! -s 10.2.0.0/16 -d 10.2.43.0/24 -j RETURN
I0914 13:21:03.493391   10227 ipmasq.go:51] Adding iptables rule: ! -s 10.2.0.0/16 -d 10.2.0.0/16 -j MASQUERADE
I0914 13:21:03.495027   10227 main.go:279] Wrote subnet file to /run/flannel/subnet.env
I0914 13:21:03.495131   10227 main.go:284] Finished starting backend.
I0914 13:21:03.495456   10227 vxlan_network.go:56] Watching for L3 misses
I0914 13:21:03.495478   10227 vxlan_network.go:64] Watching for new subnet leases
I0914 13:21:03.506884   10227 main.go:367] Waiting for 22h59m59.975782119s to renew lease
# curl  --cacert "$ETCDCTL_CACERT" --cert "$ETCDCTL_CERT" --key "$ETCDCTL_KEY" "https://192.168.56.201:22379/v2/keys/atomic.io/network/subnets/"
{"action":"get","node":{"key":"/atomic.io/network/subnets","dir":true,"nodes":[{"key":"/atomic.io/network/subnets/10.2.43.0-24","value":"{\"PublicIP\":\"192.168.56.201\",\"BackendType\":\"vxlan\",\"BackendData\":{\"VtepMAC\":\"62:bd:ec:e9:a3:a1\"}}","expiration":"2017-09-15T11:21:03.48265808Z","ttl":86385,"modifiedIndex":38,"createdIndex":38}],"modifiedIndex":7,"createdIndex":7}}
```

The interface `enp0s8` is the public interface with the ip addresses 192.168.56.200 for node-0 and 192.168.56.201 for node-1.

## Your Environment

* Flannel version: v0.8.0
* Backend used (e.g. vxlan or udp): vxlan 
* Etcd version: 3.2.5
* Operating System and version: `4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux`

**Comment by devent** [comment] 2017-09-14 11:32
Update: If I restart the nodes, a new subnet is picked. Shouldn't it be done without a restart?

node-0

```
Sep 14 13:29:44 robobee-test.test flanneld[833]: I0914 13:29:44.474993     833 main.go:229] Installing signal handlers
Sep 14 13:29:44 robobee-test.test flanneld[833]: I0914 13:29:44.552696     833 main.go:330] Found network config - Backend type: vxlan
Sep 14 13:29:44 robobee-test.test flanneld[833]: I0914 13:29:44.578382     833 local_manager.go:234] Picking subnet in range 10.2.1.0 ... 10.2.255.0
Sep 14 13:29:44 robobee-test.test flanneld[833]: I0914 13:29:44.584280     833 local_manager.go:220] Allocated lease (10.2.24.0/24) to current node (192.168.56.200)
Sep 14 13:29:44 robobee-test.test flanneld[833]: I0914 13:29:44.585051     833 main.go:279] Wrote subnet file to /run/flannel/subnet.env
Sep 14 13:29:44 robobee-test.test flanneld[833]: I0914 13:29:44.585072     833 main.go:284] Finished starting backend.
Sep 14 13:29:44 robobee-test.test flanneld[833]: I0914 13:29:44.586597     833 vxlan_network.go:56] Watching for L3 misses
Sep 14 13:29:44 robobee-test.test flanneld[833]: I0914 13:29:44.586615     833 vxlan_network.go:64] Watching for new subnet leases
Sep 14 13:29:44 robobee-test.test systemd[1]: Started Flanneld overlay address etcd agent.
Sep 14 13:29:44 robobee-test.test flanneld[833]: I0914 13:29:44.611990     833 main.go:367] Waiting for 22h59m59.967070833s to renew lease
```

node-1

```
Sep 14 13:29:45 robobee-1-test.test flanneld[776]: I0914 13:29:45.261677     776 main.go:226] Created subnet manager: Etcd Local Manager with Previous Subnet: 0.0.0.0/0
Sep 14 13:29:45 robobee-1-test.test flanneld[776]: I0914 13:29:45.261869     776 main.go:229] Installing signal handlers
Sep 14 13:29:45 robobee-1-test.test flanneld[776]: I0914 13:29:45.351221     776 main.go:330] Found network config - Backend type: vxlan
Sep 14 13:29:45 robobee-1-test.test flanneld[776]: I0914 13:29:45.378529     776 local_manager.go:147] Found lease (10.2.43.0/24) for current IP (192.168.56.201), reusing
Sep 14 13:29:45 robobee-1-test.test flanneld[776]: I0914 13:29:45.405887     776 main.go:279] Wrote subnet file to /run/flannel/subnet.env
Sep 14 13:29:45 robobee-1-test.test flanneld[776]: I0914 13:29:45.405911     776 main.go:284] Finished starting backend.
Sep 14 13:29:45 robobee-1-test.test flanneld[776]: I0914 13:29:45.406324     776 vxlan_network.go:56] Watching for L3 misses
Sep 14 13:29:45 robobee-1-test.test flanneld[776]: I0914 13:29:45.406339     776 vxlan_network.go:64] Watching for new subnet leases
Sep 14 13:29:45 robobee-1-test.test systemd[1]: Started Flanneld overlay address etcd agent.
Sep 14 13:29:45 robobee-1-test.test flanneld[776]: I0914 13:29:45.637436     776 main.go:367] Waiting for 22h59m59.741953496s to renew lease
```

**Comment by devent** [comment] 2017-09-14 12:04
I forgot to write, I had flanneld already installed on the node-0 and node-1, but the etcd cluster wasn't setup yet between the nodes. But I deleted the virtual network `flannel.1` before I reinstalled flanneld.

```
ip link delete flanneld.1
```

Maybe the reason was that the old network interfaces `flanneld.1` was still present on the nodes?

**Comment by tomdee** [comment] 2017-09-18 22:54
@devent I'm not sure what the problem is here. My guess would be that maybe both nodes ended up with a `/run/flannel/subnet.env` which told flannel to use the same lease.

It shouldn't be possible to have two flannel instances sharing the same lease so there could be a possible bug here. But I'm unclear on the exact sequence of events (how were you running flannel without etcd for example?). I don't think there's anything here that I can fix without a clearer repro, so I'm closing this until we can get some more clarity.

**Comment by devent** [comment] 2017-09-19 11:30
To clarify. The whole process was as following.
1. One Virtualbox Debian 9, lets say node-0, hostname node-0, address 192.168.56.200
2. Installed etcd, flanneld and docker on node-0, everything runs fine.
3. make a clone of node-0, with new mac address, node-1.
4. change the IP and hostname of node-1 to node-1 and 192.168.56.201, respectively.
5. stop etcd on the nodes, delete old etcd data directory on node-0 and node-1.
6. reinstall etcd, flanneld and docker on node-0 and node-1, with a new etcd cluster made of node-0 and -1.
7. flanneld on the nodes is now using the newly installed etcd cluster.
8. subnet on node-0 and node-1 is the same, with either flanneld-0 or flanneld-1 overriding the subnet configuration on the etcd-cluster, depending which node was started last.
...
9. restart both nodes, flanneld now works as expected.

My expectation was that no restart should be needed, because flanneld-0 and flanneld-1 would see the subnet in the etcd-cluster. Since I deleted the old etcd data directories on both nodes and started a fresh new etcd cluster, there should be no old configuration left.

**Comment by tomdee** [comment] 2017-09-22 08:57
Thanks @devent for the extra info. I'll need to digest this some more but reopening the issue to keep it tracked.

**Closed** 2023-02-16 17:47 UTC
Labels: kind/enhancement, kind/support, wontfix
