### ISSUE TITLE
ibnftnl.so.11.3.0 used by flannel causing kernel panic

### ISSUE THREAD

**Issue by sudheshpn** [flannel-io/flannel#1476] opened 2021-09-07 09:58 UTC
Hi 

   In our Env we are seeing few of the kubernetes nodes are getting rebooted frequently due to sigfault caused due to iptables. I see  libnftnl.so.11.3.0 is used by flannel.  Currently we are using iptables and we have not installed libnftnl and nftables packages.   Do we need to use both or use the existing legacy iptables?

Authorized uses only. All activity may be monitored and reported.
amomv0073 login: [87525.071941] iptables[20966]: segfault at 88 ip 00007f6f5e8b4e47 sp 00007ffdf8bccc18 error 4 in libnftnl.so.11.3.0[7f6f5e8b0000+16000]
[90889.066374] iptables[15143]: segfault at 88 ip 00007fccd4079e47 sp 00007ffc97a309a8 error 4 in libnftnl.so.11.3.0[7fccd4075000+16000]
[93931.501428] iptables[32105]: segfault at 88 ip 00007f7d2b71ee47 sp 00007ffd60056a78 error 4 in libnftnl.so.11.3.0[7f7d2b71a000+16000]
[95042.578955] iptables[29824]: segfault at 88 ip 00007f4129bbbe47 sp 00007ffd599f7438 error 4 in libnftnl.so.11.3.0[7f4129bb7000+16000]
[95593.215287] iptables[13048]: segfault at 88 ip 00007fe24d381e47 sp 00007ffd00b0d3e8 error 4 in libnftnl.so.11.3.0[7fe24d37d000+16000]
[98987.242761] iptables[7706]: segfault at 88 ip 00007fef88270e47 sp 00007ffc6052c148 error 4 in libnftnl.so.11.3.0[7fef8826c000+16000]
[107193.611326] BUG: unable to handle kernel NULL pointer dereference at 0000000000000030
[107193.612965] IP: switch_to_thread_stack+0x24/0x3a
[107193.614445] PGD d93533067 P4D d93533067 PUD 0
[107193.615909] Oops: 0000 [#1] SMP NOPTI
[107193.617322] Modules linked in: xt_multiport xt_set ipt_rpfilter ip_set_hash_ip ip_set_hash_net veth vxlan ip6_udp_tunnel udp_tunnel nf_conntrack_netlink xt_statistic xt_nat nft_meta xt_addrtype nft_counter nft_compat nft_chain_nat_ipv4 nft_chain_route_ipv4 nf_tables_ipv4 nf_tables ip_vs_sh ip_vs_wrr ip_vs_rr xt_comment xt_mark ip_vs overlay nfsv3 nfs_acl nfs lockd grace fscache ipt_MASQUERADE nf_nat_masquerade_ipv4 ip6t_rpfilter ip6t_REJECT nf_reject_ipv6 ipt_REJECT nf_reject_ipv4 xt_conntrack ebtable_nat ebtable_broute ip6table_nat nf_conntrack_ipv6 nf_defrag_ipv6 nf_nat_ipv6 ip6table_mangle ip6table_security ip6table_raw iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 nf_nat iptable_mangle iptable_security iptable_raw nf_conntrack ip_set nfnetlink ebtable_filter ebtables ip6table_filter
[107193.630735]  ip6_tables iptable_filter ovmapi sunrpc xfs libcrc32c sb_edac coretemp crct10dif_pclmul crc32_pclmul ghash_clmulni_intel pcbc xen_kbdfront xen_fbfront syscopyarea sysfillrect sysimgblt fb_sys_fops aesni_intel crypto_simd glue_helper cryptd binfmt_misc xenfs br_netfilter xen_privcmd bridge stp llc ip_tables ext4 mbcache jbd2 fscrypto xen_netfront xen_blkfront crc32c_intel dm_mirror dm_region_hash dm_log dm_mod
[107193.637955] CPU: 2 PID: 4410 Comm: ld-linux.so.2 Not tainted 4.14.35-2025.404.1.1.el7uek.x86_64 #2
[107193.640667] task: ffff888d934817c0 task.stack: ffffc90018c20000
[107193.642044] RIP: e030:switch_to_thread_stack+0x24/0x3a
[107193.643381] RSP: e02b:ffffc90018c23fd0 EFLAGS: 00010282
[107193.644693] RAX: 000000000000002d RBX: 0000000000000000 RCX: 00000000f7f6c000
[107193.646048] RDX: 00000000f7f90fbc RSI: 00000000f7f6e034 RDI: 0000000000000000
[107193.647388] RBP: 00000000f7f6d320 R08: 0000000000000000 R09: 0000000000000000
[107193.648699] R10: 0000000000000000 R11: 0000000000000000 R12: 0000000000000000
[107193.649977] R13: 0000000000000000 R14: 0000000000000000 R15: 0000000000000000
[107193.651239] FS:  0000000000000000(0000) GS:ffff8891a5680000(0000) knlGS:0000000000000000
[107193.652494] CS:  e033 DS: 002b ES: 002b CR0: 0000000080050033
[107193.653682] CR2: 0000000000000030 CR3: 0000001160794000 CR4: 0000000000042660
[107193.654900] Call Trace:
[107193.655977] Code: ff ff 0f 1f 44 00 00 57 eb 12 0f 20 df 0f 1f 44 00 00 48 81 e7 ff e7 ff ff 0f 22 df 48 89 e7 65 48 8b 24 25 0c 50 00 00 ff 77 38 <ff> 77 30 ff 77 28 ff 77 20 ff 77 18 ff 77 10 ff 77 08 48 8b 3f
[107193.659551] RIP: switch_to_thread_stack+0x24/0x3a RSP: ffffc90018c23fd0
[107193.660746] CR2: 0000000000000030
[107193.661889] ---[ end trace b5d8e9041865e3c8 ]---
[107193.663044] Kernel panic - not syncing: Fatal exception
[107193.664206] Kernel Offset: disabled
[107193.665298] Rebooting in 10 seconds..

## Your Environment

* Flannel version: flannel:v0.12.0
* Backend used (e.g. vxlan or udp):
* Kubernetes version (if used):  v1.18.18+2.el7
* Operating System and version:
Red Hat Enterprise Linux Server release 7.9 (Maipo)
4.14.35-2047.502.4.el7uek.x86_64

**Comment by shawnz** [comment] 2021-09-16 02:35
Perhaps a dupe of #1408 ?

**Comment by Oats87** [comment] 2021-11-04 22:43
Appears to be a duplicate of https://github.com/flannel-io/flannel/issues/1408

**Closed by Oats87** 2021-11-04 22:43 UTC
