### ISSUE TITLE
Flanneld doesn't reconnect to the apiserver

### ISSUE THREAD

**Issue by angeloxx** [flannel-io/flannel#1272] opened 2020-03-24 17:38 UTC
When flanneld 0.12 on Windows worker node lost the connection with the apiserver, it doesn't retry to connect but continues to log:

`reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:307: Failed to list *v1.Node: Get https://10.128.0.12:6443/api/v1/nodes?resourceVersion=0: http2: no cached connection was `available`

## Expected Behavior
Flanneld should reconnect to the apiserver

## Steps to Reproduce (for bugs)
In our environment the easiest way to reproduce the issue is to move the floating IP to a different master node.

## Your Environment
* Flannel version: 0.12.0
* Startup Option: --kube-subnet-mgr --kubeconfig-file=<kubelet-file.conf>
* Backend used: vxlan
* Kubernetes version (if used): 1.16.3 on premise, 3 master nodes and we're using a floating IP (managed by keepalived) that is used by flanneld as backend
* Operating System and version: 
  * Master: Redhat Linux 7
  * Worker: Windows 2019 10.0.0.17763.934

**Comment by DerrickMartinez** [comment] 2020-05-02 02:50
I have reproduced this as well in 0.12.0. When rolling updating master nodes, it will cause this to go into panic

**Comment by DerrickMartinez** [comment] 2020-05-27 23:35
Any update on this issue? It's bad enough so 0.12.0 it's not production ready in a windows env. Thanks

**Comment by luthermonson** [comment] 2020-06-16 23:57
@DerrickMartinez you have any logs you can post? i have to look into something i think is related.

**Comment by giskou** [comment] 2020-06-17 08:34
I keep seeing this when flannel starts after the host has been restarted.
Not a windows/flannel expert, but from what I understand the HCN network is lost on reboots and this starts happening only if flannel recreates the HCN.
```
I0617 10:20:41.195352    5580 main.go:518] Determining IP address of default interface
I0617 10:20:41.804639    5580 main.go:531] Using interface with name Ethernet0 and address 172.16.13.197
I0617 10:20:41.804639    5580 main.go:548] Defaulting external address to interface address (172.16.13.197)
I0617 10:20:41.840550    5580 kube.go:119] Waiting 10m0s for node controller to sync
I0617 10:20:41.840550    5580 kube.go:306] Starting kube subnet manager
I0617 10:20:42.849946    5580 kube.go:126] Node controller sync successful
I0617 10:20:42.850188    5580 main.go:246] Created subnet manager: Kubernetes Subnet Manager - windows-worker-08
I0617 10:20:42.850188    5580 main.go:249] Installing signal handlers
I0617 10:20:42.850188    5580 main.go:390] Found network config - Backend type: vxlan
I0617 10:20:42.850188    5580 vxlan_windows.go:127] VXLAN config: Name=flannel.4096 MacPrefix=0E-2A VNI=4096 Port=4789 GBP=false DirectRouting=false
I0617 10:20:42.920661    5580 device_windows.go:116] Attempting to create HostComputeNetwork &{ flannel.4096 Overlay [] {[]} { [] [] []} [{Static [{10.244.21.0/24 [[123 34 84 121 112 101 34 58 34 86 83 73 68 34 44 34 83 101 116 116 105 110 103 115 34 58 123 34 73 115 111 108 97 116 105 111 110 73 100 34 58 52 48 57 54 125 125]] [{10.244.21.1 0.0.0.0/0 0}]}]}] 8 {2 0}}
E0617 10:20:43.940915    5580 streamwatcher.go:109] Unable to decode an event from the watch stream: read tcp 172.16.13.197:57186->172.16.11.83:6443: wsarecv: An established connection was aborted by the software in your host machine.
E0617 10:20:43.940915    5580 reflector.go:304] github.com/coreos/flannel/subnet/kube/kube.go:307: Failed to watch *v1.Node: Get https://172.16.11.83:6443/api/v1/nodes?resourceVersion=40721785&timeoutSeconds=582&watch=true: http2: no cached connection was available
E0617 10:20:44.940478    5580 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:307: Failed to list *v1.Node: Get https://172.16.11.83:6443/api/v1/nodes?resourceVersion=0: http2: no cached connection was available
E0617 10:20:45.954628    5580 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:307: Failed to list *v1.Node: Get https://172.16.11.83:6443/api/v1/nodes?resourceVersion=0: http2: no cached connection was available
E0617 10:20:46.954301    5580 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:307: Failed to list *v1.Node: Get https://172.16.11.83:6443/api/v1/nodes?resourceVersion=0: http2: no cached connection was available
E0617 10:20:47.953842    5580 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:307: Failed to list *v1.Node: Get https://172.16.11.83:6443/api/v1/nodes?resourceVersion=0: http2: no cached connection was available
I0617 10:20:48.376730    5580 device_windows.go:124] Waiting to get ManagementIP from HostComputeNetwork flannel.4096
I0617 10:20:48.877389    5580 device_windows.go:136] Waiting to get net interface for HostComputeNetwork flannel.4096 (172.16.13.197)
E0617 10:20:48.954487    5580 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:307: Failed to list *v1.Node: Get https://172.16.11.83:6443/api/v1/nodes?resourceVersion=0: http2: no cached connection was available
I0617 10:20:49.581533    5580 device_windows.go:145] Created HostComputeNetwork flannel.4096
I0617 10:20:49.584529    5580 main.go:313] Changing default FORWARD chain policy to ACCEPT
I0617 10:20:49.587538    5580 main.go:321] Wrote subnet file to /run/flannel/subnet.env
I0617 10:20:49.587538    5580 main.go:325] Running backend.
I0617 10:20:49.587538    5580 main.go:343] Waiting for all goroutines to exit
I0617 10:20:49.587538    5580 vxlan_network_windows.go:63] Watching for new subnet leases
E0617 10:20:49.954382    5580 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:307: Failed to list *v1.Node: Get https://172.16.11.83:6443/api/v1/nodes?resourceVersion=0: http2: no cached connection was available
E0617 10:20:50.957178    5580 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:307: Failed to list *v1.Node: Get https://172.16.11.83:6443/api/v1/nodes?resourceVersion=0: http2: no cached connection was available
........
........
```

If the flannel pod is removed, then on the second run it will find the HCN there and everything seems to work fine
```
I0617 10:26:30.296010    2876 main.go:518] Determining IP address of default interface
I0617 10:26:30.796195    2876 main.go:531] Using interface with name vEthernet (Ethernet0) and address 172.16.13.197
I0617 10:26:30.796195    2876 main.go:548] Defaulting external address to interface address (172.16.13.197)
I0617 10:26:30.822208    2876 kube.go:119] Waiting 10m0s for node controller to sync
I0617 10:26:30.822208    2876 kube.go:306] Starting kube subnet manager
I0617 10:26:31.823168    2876 kube.go:126] Node controller sync successful
I0617 10:26:31.823168    2876 main.go:246] Created subnet manager: Kubernetes Subnet Manager - windows-worker-08
I0617 10:26:31.823168    2876 main.go:249] Installing signal handlers
I0617 10:26:31.823168    2876 main.go:390] Found network config - Backend type: vxlan
I0617 10:26:31.823168    2876 vxlan_windows.go:127] VXLAN config: Name=flannel.4096 MacPrefix=0E-2A VNI=4096 Port=4789 GBP=false DirectRouting=false
I0617 10:26:31.872028    2876 device_windows.go:102] Found existing HostComputeNetwork flannel.4096
I0617 10:26:31.907033    2876 main.go:313] Changing default FORWARD chain policy to ACCEPT
I0617 10:26:31.909029    2876 main.go:321] Wrote subnet file to /run/flannel/subnet.env
I0617 10:26:31.909029    2876 main.go:325] Running backend.
I0617 10:26:31.909029    2876 vxlan_network_windows.go:63] Watching for new subnet leases
I0617 10:26:31.909029    2876 main.go:343] Waiting for all goroutines to exit

**Comment by EagleIJoe** [comment] 2020-06-17 09:22
Windows Update KB4551853 screws up my flannel connections. Could be related. Is not only related to flannel but also affects other CNI (ex Docker swarm).

**Comment by KnicKnic** [comment] 2020-06-19 22:41
I have a workaround for this issue, see https://github.com/KnicKnic/flannel/commit/023f21b2ef2b1fa9204aae0fe63ba9ab82e3aa64

**Comment by jsturtevant** [comment] 2020-10-15 16:13
This looks to be an open standing issue with the golang client: https://github.com/kubernetes/client-go/issues/374

It looks like this type of failure is handled directly in kubelet as a workaround: https://github.com/kubernetes/kubernetes/pull/78016 and other CNI's handle it as well: https://github.com/AliyunContainerService/terway/pull/87

**Comment by rhockenbury** [comment] 2020-11-21 04:31
With https://github.com/kubernetes/kubernetes/pull/95981 merged, I believe all that needs to be done to resolve this is bumping k8s.io/go-client to 1.20 after release or the 1.19 backport.

**Comment by rhockenbury** [comment] 2020-11-21 19:14
And the cherrypick PR for 1.19 is now open - https://github.com/kubernetes/kubernetes/pull/96778

1.19.5 is slated for release on 12/9 per https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md.

**Closed** 2023-02-15 23:43 UTC
Labels: wontfix
